name: auto_tagger
on:
  pull_request:
   types: [closed]
jobs:
  build:
    if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        # https://github.com/semantic-release/semantic-release/discussions/2557
        persist-credentials: false
    - name: Github PR Auto Tagger
      uses: RueLaLa/auto-tagger@v2.1.3
      env:
        GITHUB_TOKEN: ${{ secrets.AUTO_TAGGER_TOKEN }}
        GITHUB_PR_NUMBER: ${{ github.event.number }}