name: Base images
on: pull_request
env:
  DOCKER_CLI_EXPERIMENTAL: 'enabled'
jobs:
  # Use un-authenticated ephemeral registry image uri for testing
  ttl-sh:
    runs-on: ubuntu-22.04
    outputs:
      uri: ${{ steps.image-uri.outputs.uri }}
    steps:
      - id: image-uri
        run: echo "uri=ttl.sh/${{ github.repository }}/$(cat /proc/sys/kernel/random/uuid)" >> $GITHUB_OUTPUT
  test:
    runs-on: ubuntu-22.04
    needs: [ttl-sh]
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2
      - uses: ./buildpacks/create-multi-arch-builders
        with:
          path: 'buildpacks/create-multi-arch-builders/testdata'
          base-image-uri: ${{ needs.ttl-sh.outputs.uri }}
      - name: Test mulit-arch builders
        run: |
          #!/usr/bin/env bash -euo pipefail

          cd buildpacks/create-multi-arch-builders/testdata

          # Gets tag from builder toml files following naming pattern `builder-<tag>.toml`
          tags=$(ls *.toml | xargs -n1 | cut -d- -f2 | cut -d. -f1 | xargs)

          set -x

          for tag in $tags; do
              image_tag="${{ needs.ttl-sh.outputs.uri }}:${tag}"
              docker buildx build \
                  --platform linux/amd64,linux/arm64 \
                  --tag not-pushing-so-this-is-ignored \
                  - <<TEST-DOCKERFILE-EOF
          FROM ${image_tag}
          RUN arch && /cnb/lifecycle/lifecycle -version
          TEST-DOCKERFILE-EOF

          done