name: podman_poc
on: pull_request
jobs:
  poc:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v2
      - id: install-podman
        run: |
          sudo apt update
          sudo apt upgrade -y

          # sudo apt install -y libvirt-daemon
          # sudo systemctl enable libvirtd
          # sudo systemctl start libvirtd

          sudo apt-get install -y qemu-user qemu-user-binfmt qemu-system-x86 qemu-system-arm
          sudo apt-get install -y podman

          arm64_coreos_archive_name=fedora-coreos-38.20230709.3.0-qemu.aarch64.qcow2.xz
          curl -O https://builds.coreos.fedoraproject.org/prod/streams/stable/builds/38.20230709.3.0/aarch64/$arm64_coreos_archive_name

          podman machine ls
          podman machine init --image-path $arm64_coreos_archive_name arm64
          podman system connection default arm64
          podman machine start arm64
          podman machine ls

          docker pull ubuntu:jammy
          docker run --rm ubuntu:jammy arch

          podman pull ubuntu:jammy
          podman run --rm ubuntu:jammy arch
