name: podman_poc
on: pull_request
jobs:
  poc:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v2
      - id: install-podman
        run: |
          sudo apt-get update
          sudo apt-get install -y podman
          arm64_coreos_archive_name=fedora-coreos-38.20230709.3.0-qemu.aarch64.qcow2.xz
          curl -O https://builds.coreos.fedoraproject.org/prod/streams/stable/builds/38.20230709.3.0/aarch64/$arm64_coreos_archive_name
          podman machine init --image-path $arm64_coreos_archive_name arm64
          podman system connection default arm64
          podman machine start arm64
          podman machine ls
          
          docker run --rm ubuntu:jammy arch
          
          podman pull ubuntu:jammy
          podman run --rm ubuntu:jammy arch